language: scala

scala:
- 2.11.8
- 2.12.0

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

script:
- sbt ++$TRAVIS_SCALA_VERSION test

env:
  global:

after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
